### PR TITLE
TASK: Use correct description for nl2br ViewHelper

### LINKED ISSUE #1831: Wrong desricption for nl2br ViewHelper
### Description

The description for the Nl2brViewHelper says "text with line breaks replaced by <br />".
This is wrong. The php function nl2br adds a <br /> before the newline character and do
not replace it.

### Affected Versions
All

### PR DESCRIPTION
**Pull request by sorenmalling**
Use correct description of the nl2br functionality from php.net/nl2br

Resolves #1831

### CODE REVIEW

File: Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php [hunk 1]
```diff
@@ -26,14 +26,14 @@
  * <f:format.nl2br>{text_with_linebreaks}</f:format.nl2br>
  * </code>
  * <output>
- * text with line breaks replaced by <br />
+ * newline characters in a string get's prefixed with <br /> to create linebreak
```
Comment (albe) [inline Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php]:
```suggestion
 * newline characters in a string get prefixed with <br /> to create linebreak
```

File: Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php [hunk 2]
```diff
@@ -26,14 +26,14 @@
...
  * </output>
  *
  * <code title="Inline notation">
  * {text_with_linebreaks -> f:format.nl2br()}
  * </code>
  * <output>
- * text with line breaks replaced by <br />
+ * newline characters in a string get's prefixed with <br /> to create linebreak
```
Comment (albe) [inline Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php]:
```suggestion
 * newline characters in a string get prefixed with <br /> to create linebreak
```
