### PR TITLE
BUGFIX: Do proper resolving of FusionPathProxy

### LINKED ISSUE #3357: BUG: Fluid does not correctly resolve path references on FusionPathProxy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is probably a variant of an issue thought to be fixed with #3041.

As I found out today, this does not work when you use {image.title} in Fluid and image is a FusionPathProxy:

1. `StandardVariableProvider` checks for `ArrayAccess`, `FusionPathProxy` provides that. `offsetExists()` and `offsetGet()` only check for the offset directly in the partial fusion tree – there we have no title
2. Now `$subject` is an object (our `FusionPathProxy`), but has no matching get/set/is/property
3. Our `TemplateVariableContainer` is getting null back, and thus exits in https://github.com/neos/flow-development-collection/blob/129306a2f5374c07c6b2450b1a5ccf649f16892a/Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php#L37 – that results in null again.
4. title ends up as null

### Expected Behavior

The title should be taken from the assigned image.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow: 9.0.0-beta10
- PHP: 8.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kdambekalns**
Using `{image.title}` in Fluid when the image is a `FusionPathProxy` does not work. The result is simply `null` instead of the image title.

This change fixes that by moving more code down into our own custom `TemplateVariableContainer` from the `StandardVariableProvider`.

Fixes neos/flow-development-collection#3357

**Review instructions**

The fixed issue contains instructions on how to reproduce this.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] ~The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)~
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] ~Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions~

### CODE REVIEW

File: Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php [hunk 1]
```diff
@@ -13,32 +14,77 @@
...
 use TYPO3Fluid\Fluid\Core\Variables\StandardVariableProvider;
-use TYPO3Fluid\Fluid\Core\Variables\VariableProviderInterface;
 
 /**
  * Provides the variables inside fluid template. Adds TemplateObjectAccessInterface functionality.
  *
  * @api
  */
-class TemplateVariableContainer extends StandardVariableProvider implements VariableProviderInterface
+class TemplateVariableContainer extends StandardVariableProvider
```
Comment (kdambekalns) [inline Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php:23]: The interface is implemented by the extended class already…

File: Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php [hunk 2]
```diff
@@ -13,32 +14,77 @@
...
+                if (method_exists($subject, $getMethod)) {
+                    $subject = $subject->$getMethod();
+                    continue;
+                }
+                $isMethod = 'is' . $upperCasePropertyName;
+                if (method_exists($subject, $isMethod)) {
+                    $subject = $subject->$isMethod();
+                    continue;
+                }
+                $hasMethod = 'has' . $upperCasePropertyName;
```
Comment (mhsdesign) [inline Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php:64]: is it worth a consideration to use object access here?
And also can it be that we lost certain features over time in fluid like https://github.com/neos/flow-development-collection/pull/108?
I cant really judge and am not that invested into it and neither know whats best. But it seems its a bit back and forth ... we seemed to had already such manual implementation once and it got lost it seems?

**Comment by dlubitz** [comment]
Looks reasonable to me.

**Review by dlubitz — APPROVED** [review]

File: Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php (hunk 2 above)
Comment (kdambekalns) [reply Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php:64]: I did very consciously copy the method as unchanged as possible, to make the difference clearly visible and easy to understand. This will make maintenance easier for our future selves.

About #108 – yes, it seems that was lost. But given the decline of Fluid, I have little interest in fixing that nowish, and certainly not in the scope of this PR…
